### ISSUE TITLE
mensaje error

### ISSUE THREAD

**Issue by byron1712** [udearroba/cohortes-admin#48]
al editar una entrada y darle guardar, sale el mensaje de error de fecha de formato, que ya estaba grabada y no graba la modificación realizada
![image](https://user-images.githubusercontent.com/32398612/63030578-281f3e80-be78-11e9-9332-97eba2a54ba2.png)

**Comment by DanielJaramillo94** [comment]
Por favor prueba si el error sigue ocurriendo en la nueva versión.
A mí me está funcionando bien.
