### ISSUE TITLE
Estado de la ocurrencia

### ISSUE THREAD

**Issue by soporte3ude** [udearroba/cohortes-admin#65]
El Estado de la ocurrencia podría traer por defecto la palabra Finalizado? Ya que todas las ocurrencias se registran cuando ya han finalizado.

**Comment by DanielJaramillo94** [comment]
Por supuesto. Esto ya ha sido reportado [aquí](https://github.com/udearroba/cohortes-admin/issues/46), y solucionado.
Sale en la próxima versión de la página.
