### ISSUE TITLE
completar información de reunion

### ISSUE THREAD

**Issue by byron1712** [udearroba/cohortes-admin#68]
al iniciar a ingresar la información de una reunión y grabarla, la aplicación nos devuelve a la ventana donde se puede ingresar la información de otra reunión, entonces, toca bajar para buscar la reunión que acabamos de crear para continuar agregando las ocurrencias y demás, ahora no es tan conflictivo pues son pocas las reuniones que se han creado, pero cuando ya estén ingresadas cientos de reuniones, hasta donde habría que bajar? sería bueno que darle agregar a la información inicial de una reunión, por defecto nos deje en la ventana para ingresar las ocurrencias de esa reunión, para así continuar el proceso si tener que buscar cual fue la que ingrese

**Comment by DanielJaramillo94** [comment]
Hola Byron.
Cuando ingresas una reunión, aparece una notificación en color verde donde dice 'Agregar ocurrencia', sí le das click ahí, vas directamente al formulario para agregarle una ocurrencia a la reunión recién creada.

**Comment by byron1712** [comment]
a si, ya la vi, pero dura muy poco, si se no damos click de inmediato, pailas

**Comment by DanielJaramillo94** [comment]
Actualmente la notificación dura 5 segundos.

**Comment by byron1712** [comment]
entonces por favor deja dos botones, el que está ahora y otro que diga agregar e ir a ocurrencias, pues el aviso se nos puede pasar, si en ese momento entro una llamada, alguien nos pregunta algo, ya tendríamos que ir hasta el final de la lista
