### ISSUE TITLE
URL start debe ser igual a URL join

### ISSUE THREAD

**Issue by byron1712** [udearroba/cohortes-admin#70]
la URL Join está quedando con los guiones que separan los números

**Comment by byron1712** [comment]
perdon, es la url start

**Comment by byron1712** [comment]
![image](https://user-images.githubusercontent.com/32398612/64272249-95b50c80-cf04-11e9-9f3a-09b828da1fbc.png)

**Comment by DanielJaramillo94** [comment]
¿Cuál es es formato de este campo? ¿Es lo mismo que URL join?
Si no son lo mismo, ¿cuál es la diferencia?

**Comment by byron1712** [comment]
por ahora queda el mismo dato

**Comment by DanielJaramillo94** [comment]
Resuelto en 7609fb295389ef2205cc1e9fcbc7429c13fc9e3d
