### ISSUE TITLE
Hora de la ocurrencia

### ISSUE THREAD

**Issue by soporte3ude** [udearroba/cohortes-admin#72]
La hora de la ocurrencia continua sin guardar como la ingreso, por ejemplo ingreso en la hora 5:59 am y al actualizar queda 12:59 AM 

![image](https://user-images.githubusercontent.com/54545646/64274036-2c36fd00-cf08-11e9-961a-ea216040982b.png)

**Comment by DanielJaramillo94** [comment]
Hola,
a mí sí me está funcionando bien
![bug_durationPicker](https://user-images.githubusercontent.com/29381519/64360865-f90c7080-cfd0-11e9-9399-3799d1eb78c7.gif)

**Comment by soporte3ude** [comment]
Acá ingreso la hora 8:10 am

![image](https://user-images.githubusercontent.com/54545646/64362278-d9c31280-cfd3-11e9-9d57-c46ae0fac835.png)

Cuando le doy agregar, efectivamente queda con la hora que ingresé 8:10 am

![image](https://user-images.githubusercontent.com/54545646/64362330-f2332d00-cfd3-11e9-9681-7f53e0981f6d.png)

Pero cuando actualizo o ingreso otra ocurrencia, voy y miro y me aparece con una hora diferente

![image](https://user-images.githubusercontent.com/54545646/64362374-0b3bde00-cfd4-11e9-9dde-84c3d9fdec9c.png)

**Comment by DanielJaramillo94** [comment]
No puedo reproducir el error en mi máquina local; @mariozan1992 propone que puede ser una configuración en la base de datos. Queda pendiente de revisar.

**Comment by DanielJaramillo94** [comment]
Error corregido en [este commit](https://github.com/udearroba/cohortes-admin/commit/f6e97b1105acae1725d8d4aba40b1a323eccbd7f).
