### ISSUE TITLE
Id sistema externo y URL Start

### ISSUE THREAD

**Issue by soporte3ude** [udearroba/cohortes-admin#75]
Hola, es posible que al ingresar el UUID automáticamente se ingresen también el ID sistema externo y la URL Start que es la misma URL Join?

![image](https://user-images.githubusercontent.com/54545646/65445937-ebd8e980-ddf8-11e9-9877-1c100ec689e6.png)

**Comment by DanielJaramillo94** [comment]
Hay dos funcionalidades diferentes en este issue, por lo que se separa.
Ver #70 y #81.
