### ISSUE TITLE
Modificar grabación

### ISSUE THREAD

**Issue by soporte3ude** [udearroba/cohortes-admin#76]
Cuando vamos a modificar el enlace de la grabación, sale un mensaje que dice que la duración ingresada en "Duración" no tiene el formato correcto y no me realiza el cambio del enlace hasta que no ingrese de nuevo la duración

![image](https://user-images.githubusercontent.com/54545646/65449452-a0c2d480-de00-11e9-9333-262a8868107b.png)

**Comment by DanielJaramillo94** [comment]
El formato para ingresar la duración es [hora]:[minutos]:[segundos].
