### ISSUE TITLE
Editar enlace de archivos

### ISSUE THREAD

**Issue by soporte3ude** [udearroba/cohortes-admin#77]
Cuando se va a editar el enlace de un archivo que ya se habia ingresado, sale un mensaje de error que dice: El peso ingresado en "Peso" no tiene el formato correcto y no me realiza el cambio en el enlace hasta que no ingrese de nuevo el peso

![image](https://user-images.githubusercontent.com/54545646/65449790-4b3af780-de01-11e9-9512-e62923f6a049.png)

**Comment by DanielJaramillo94** [comment]
A mí sí me está dejando modificar los enlaces. 😶
