### ISSUE TITLE
Conversión de peso del archivo

### ISSUE THREAD

**Issue by soporte4ude** [udearroba/cohortes-admin#79]
El sistema hace una conversión del peso del archivo, al entrar a editar la url de drive ya no reconoce esta conversión dice" el peso ingresado "peso" no tiene el formato correcto"

**Comment by DanielJaramillo94** [comment]
Las automatizaciones con la parte de Drive y Zoom no hacen parte de esta versión.

**Comment by DanielJaramillo94** [comment]
¿El error persiste? Por favor reabrir si la respuesta es afirmativa.
