### ISSUE TITLE
No reconoce el peso de la grabación

### ISSUE THREAD

**Issue by soporte4ude** [udearroba/cohortes-admin#86]
Cuando ingreso a un ocurrencia para modificar el enlace del archivo (drive), el peso del archivo que esta predeterminado, sin modificarlo
 le doy clic a guardar cambios y me dice que el peso que ingreso no esta e un formato valido.

**Comment by DanielJaramillo94** [comment]
A mí me está dejando editar bien los pesos en los archivos.
Puedes reabrir este issue si el error persiste.
